# Generated by Django 4.2.5 on 2023-10-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fergana', 'Fargʻona viloyati'), ('jizzakh', 'Jizzax viloyati'), ('khorazm', 'Xorazm viloyati'), ('namangan', 'Namangan viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('qoraqalpoq', 'Qoraqalpogʻiston Respublikasi'), ('samarkand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('tashkent', 'Toshkent viloyati')], max_length=100)),
                ('city', models.CharField(max_length=200, verbose_name='shahar nomini kiritishi kerak')),
                ('village', models.CharField(max_length=200, verbose_name='qishloq yoki shahar nomini kiritishi kerak')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('blocklist', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
