# Generated by Django 4.2.3 on 2023-09-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(to='books.books'),
        ),
    ]
