# Generated by Django 4.2.3 on 2023-09-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0002_userprofile_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='books.books'),
        ),
    ]
