# Generated by Django 4.2.5 on 2023-10-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('swap', models.BooleanField(default=True)),
                ('to_sell', models.BooleanField(default=False)),
                ('lang', models.CharField(choices=[('ru', 'Rus tili'), ('uz', "O'zbek tili"), ('ar', 'Arab tili'), ('tr', 'Turk tili'), ('eng', 'Ingliz  tili')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/books')),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesBooks', to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_time', models.DateTimeField(auto_now_add=True)),
                ('sell', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='users.userprofile')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(blank=True, to='books.genre', verbose_name='Janrlar'),
        ),
        migrations.AddField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
