# Generated by Django 4.2.5 on 2023-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='swap_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
