# Generated by Django 4.2 on 2023-10-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_exchange_swap_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookexchange', to='books.books'),
        ),
    ]
