# Generated by Django 4.2 on 2023-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_exchange_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
