# Generated by Django 4.2 on 2023-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='lang',
            field=models.CharField(choices=[('Rus tili', 'Rus tili'), ("O'zbek tili", "O'zbek tili"), ('Arab tili', 'Arab tili'), ('Turk tili', 'Turk tili'), ('Ingliz  tili', 'Ingliz  tili')], max_length=100),
        ),
    ]
