# Generated by Django 4.2 on 2023-10-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
