# Generated by Django 4.2 on 2023-10-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0010_alter_books_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklikes', to='books.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikes', to='users.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booklikes',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='userLike'),
        ),
    ]
